; Applesoft BASIC for HBC-56 - Interpreter
;
; Executes bytecode generated by the tokenizer
;

; Zero page allocations
interp_pc          = $28   ; Program counter in bytecode
interp_sp          = $2A   ; Stack pointer
for_depth          = $2B   ; FOR loop nesting depth
gosub_depth        = $2C   ; GOSUB nesting depth
current_stmt       = $2D   ; Current statement token
eval_left_a        = $2E   ; Expression evaluator: left operand (low byte)
eval_left_x        = $2F   ; Expression evaluator: left operand (high byte)
eval_right_a       = $30   ; Expression evaluator: right operand (low byte)
eval_right_x       = $31   ; Expression evaluator: right operand (high byte)
eval_op            = $32   ; Expression evaluator: operator type

; Variable storage area
*=$0200
variable_table:
    !fill 256, 0            ; Variables: max 32 variables

; String pool
*=$0300
string_pool:
    !fill 4096, 0           ; String storage: 4KB

; GOSUB return stack
*=$1300
gosub_stack:
    !fill 64, 0             ; 32 return addresses (2 bytes each)

; FOR loop stack
*=$1340
for_stack:
    !fill 64, 0             ; 16 FOR contexts (4 bytes each)

; User program bytecode
*=$1400
program_buffer:
    !fill 30720, 0          ; User program: ~30KB max

; =============================================================================
; interpret: Main bytecode interpreter loop
; Input:  program_buffer = bytecode
; Output: (program terminates)
; =============================================================================
interpret:
    php
    pha
    phx
    phy
    
    lda #0
    sta for_depth
    sta gosub_depth
    sta interp_pc
    sta interp_pc+1
    
    ; Fetch-decode-execute loop
exec_loop:
    lda (interp_pc)
    
    ; Check if this is a line number (TOKEN_NUMBER at statement start)
    cmp #TOKEN_NUMBER
    beq skip_line_number
    
    ; Dispatch on keyword value
    cmp #KW_PRINT
    beq do_print
    cmp #KW_INPUT
    beq do_input
    cmp #KW_LET
    beq do_let
    cmp #KW_GOTO
    beq do_goto
    cmp #KW_IF
    beq do_if
    cmp #KW_FOR
    beq do_for
    cmp #KW_NEXT
    beq do_next
    cmp #KW_GOSUB
    beq do_gosub
    cmp #KW_RETURN
    beq do_return
    cmp #KW_REM
    beq do_rem
    cmp #KW_END
    beq do_end
    
    ; Skip unknown token
    bra next_token
    
skip_line_number:
    ; Line number is TOKEN_NUMBER (msb, lsb) - skip 3 bytes
    ; Then loop back to get actual statement keyword
    inc interp_pc
    inc interp_pc
    inc interp_pc
    bra exec_loop
    
do_print:
    jsr stmt_print
    bra next_token
do_input:
    jsr stmt_input
    bra next_token
do_let:
    jsr stmt_let
    bra next_token
do_goto:
    jsr stmt_goto
    bra next_token
do_if:
    jsr stmt_if
    bra next_token
do_for:
    jsr stmt_for
    bra next_token
do_next:
    jsr stmt_next
    bra next_token
do_gosub:
    jsr stmt_gosub
    bra next_token
do_return:
    jsr stmt_return
    bra next_token
do_rem:
    jsr stmt_rem
    bra next_token
do_end:
    jsr stmt_end
    bra next_token
    
    ; Move to next token
next_token:
    inc interp_pc
    bne exec_loop
    inc interp_pc+1
    bra exec_loop

; =============================================================================
; Helper functions
; =============================================================================

; output_char: Output a single character
; Input:  A = character to output
; For Phase 1, this outputs to console via emulator
output_char:
    php
    pha
    
    ; TODO: Implement actual TMS9918A output
    ; For now, just return
    
    pla
    plp
    rts

; output_hex_byte: Output a single byte as two hex digits
; Input:  A = byte to output
output_hex_byte:
    php
    pha
    
    ; High nibble
    lsr                     ; Shift right 4 times to get high nibble
    lsr
    lsr
    lsr
    jsr output_hex_digit
    
    ; Low nibble
    pla
    and #$0F                ; Mask low nibble
    jsr output_hex_digit
    
    pla
    plp
    rts

; output_hex_digit: Output a single hex digit (0-F)
; Input:  A = nibble value (0-15)
output_hex_digit:
    php
    pha
    
    cmp #10
    bcc hex_digit_0_9
    ; A-F
    adc #55                 ; #'A' - 10 = 55
    bra hex_output
hex_digit_0_9:
    adc #48                 ; #'0' = 48
hex_output:
    jsr output_char
    
    pla
    plp
    rts

; =============================================================================
; Statement handlers - dispatched by keyword token
; =============================================================================

; PRINT - output text/expressions to screen
stmt_print:
    php
    pha
    phx
    phy
    
    ; Evaluate the expression after PRINT
    inc interp_pc
    
    ; Evaluate the expression (could be number, variable, or computation)
    jsr eval_expr
    
    ; Result is now in X (high) / A (low)
    ; Store result for output
    sta eval_left_a         ; Low byte
    stx eval_left_x         ; High byte
    
    ; Output the result as a decimal number
    ; For Phase 1: output as decimal text (simple approach)
    
    ; Get the 16-bit result back
    lda eval_left_a
    ldx eval_left_x
    
    ; Output "PRINT: " indicator
    lda #80                 ; 'P'
    jsr output_char
    lda #82                 ; 'R'
    jsr output_char
    lda #73                 ; 'I'
    jsr output_char
    lda #78                 ; 'N'
    jsr output_char
    lda #84                 ; 'T'
    jsr output_char
    lda #32                 ; space
    jsr output_char
    lda #58                 ; ':'
    jsr output_char
    lda #32                 ; space
    jsr output_char
    
    ; For now, output the result as hex: "0x1234"
    ; Later phases can do proper decimal output
    lda #48                 ; '0'
    jsr output_char
    lda #120                ; 'x'
    jsr output_char
    
    ; Output high byte (X contains high byte)
    txa                     ; Transfer X to A
    jsr output_hex_byte
    
    ; Output low byte
    lda eval_left_a
    jsr output_hex_byte
    bra print_continue
    
print_continue:
    ; Next token should be delimiter (newline)
    inc interp_pc
    lda (interp_pc)         ; Should be TOKEN_DELIMITER
    
    ; Skip it
    inc interp_pc
    lda (interp_pc)         ; Delimiter type
    
    ; For now, output a newline character
    lda #10                 ; LF
    jsr output_char
    
    ply
    plx
    pla
    plp
    rts

; LET - variable assignment
stmt_let:
    php
    pha
    phx
    phy
    
    ; Format: LET variable = expression
    ; Bytecode: KW_LET, TOKEN_VARIABLE, var_index, TOKEN_OPERATOR, OP_EQUAL, [expression]
    
    inc interp_pc
    
    ; Get variable index
    lda (interp_pc)         ; Should be TOKEN_VARIABLE
    cmp #TOKEN_VARIABLE
    bne let_error
    
    inc interp_pc
    lda (interp_pc)         ; Variable index
    sta $33                 ; Save variable index for later
    
    ; Next should be TOKEN_OPERATOR with OP_EQUAL
    inc interp_pc
    lda (interp_pc)         ; Should be TOKEN_OPERATOR
    cmp #TOKEN_OPERATOR
    bne let_error
    
    inc interp_pc
    lda (interp_pc)         ; Should be OP_EQUAL
    cmp #OP_EQUAL
    bne let_error
    
    ; Now evaluate the right-hand side expression
    inc interp_pc
    jsr eval_expr
    
    ; Result in X (high) / A (low)
    ; Variable index in $33
    ; Store result in variable table at $0200
    pha                     ; Save low byte
    txa                     ; Move high byte to A
    ldx $33
    asl                     ; *2 for 2-byte variable
    tax
    sta $0200, x            ; Store high byte at $0200+2*var_index
    pla                     ; Restore low byte
    sta $0201, x            ; Store low byte at $0201+2*var_index
    
    ; Skip to end of statement (next delimiter/newline)
    ; eval_expr already advanced past the expression
    
let_error:
    ply
    plx
    pla
    plp
    rts

; INPUT - read from keyboard
stmt_input:
    php
    pha
    
    ; For Phase 1: stub
    ; TODO: Implement keyboard input
    
    pla
    plp
    rts

; GOTO - unconditional jump
; GOTO - unconditional jump to line number
stmt_goto:
    php
    pha
    phx
    phy
    
    ; Next token should be line number
    inc interp_pc
    lda (interp_pc)
    
    ; Check if it's a number token
    cmp #TOKEN_NUMBER
    bne goto_error
    
    ; Get line number (next 2 bytes)
    inc interp_pc
    lda (interp_pc)         ; High byte of line number
    sta work_b
    inc interp_pc
    lda (interp_pc)         ; Low byte
    sta work_a
    
    ; Now search for this line number in the bytecode
    ; Start from program_buffer ($1400)
    lda #<program_buffer
    sta tokenizer_ptr
    lda #>program_buffer
    sta tokenizer_ptr+1
    
    ; Scan through bytecode looking for matching line number
    ; For Phase 1: simple linear scan
    jsr find_line
    
    ; If found, update program counter
    lda tokenizer_ptr
    sta interp_pc
    lda tokenizer_ptr+1
    sta interp_pc+1
    
goto_error:
    ply
    plx
    pla
    plp
    rts

; find_line: Find a line number in bytecode
; Input:  work_a:work_b = line number to find
;         tokenizer_ptr = start address
; Output: tokenizer_ptr = address if found
; For Phase 1, stub implementation
find_line:
    rts

; IF - conditional branch
stmt_if:
    php
    pha
    phx
    phy
    
    ; Parse: IF expression THEN line_number
    ; For Phase 1: simplified - just skip the statement
    
    ply
    plx
    pla
    plp
    rts

; THEN - part of IF statement
stmt_then:
    rts

; FOR - start loop
stmt_for:
    php
    pha
    phx
    phy
    
    ; FOR var = start TO end [STEP step]
    ; For Phase 1: simplified - just skip the statement
    ; TODO: Push loop context to FOR stack
    
    ply
    plx
    pla
    plp
    rts

; NEXT - end loop
stmt_next:
    php
    pha
    phx
    phy
    
    ; NEXT var
    ; For Phase 1: simplified - just skip the statement
    ; TODO: Pop loop context, check condition, jump back or continue
    
    ply
    plx
    pla
    plp
    rts

; GOSUB - call subroutine
stmt_gosub:
    php
    pha
    phx
    phy
    
    ; GOSUB line_number
    ; For Phase 1: simplified - just skip
    ; TODO: Push return address to GOSUB stack, jump to line
    
    ply
    plx
    pla
    plp
    rts

; RETURN - return from subroutine
stmt_return:
    php
    pha
    phx
    phy
    
    ; Return to caller
    ; For Phase 1: simplified - just skip
    ; TODO: Pop return address from GOSUB stack
    
    ply
    plx
    pla
    plp
    rts

; REM - comment (already skipped by tokenizer)
stmt_rem:
    php
    pha
    phx
    phy
    
    ; REM statement: skip everything until newline
    ; Keep scanning bytecode until we find NEWLINE
    
rem_loop:
    inc interp_pc
    lda (interp_pc)
    
    ; Check for end of line markers
    cmp #TOKEN_DELIMITER
    bne rem_loop
    
    ; Got a delimiter, check if it's newline
    inc interp_pc
    lda (interp_pc)
    cmp #DELIM_NEWLINE
    bne rem_loop
    
    ; Found newline, we're done
    ply
    plx
    pla
    plp
    rts

; END - terminate program
stmt_end:
    rts

; RUN - start execution
stmt_run:
    rts

; NEW - clear program
stmt_new:
    rts

; PLOT - graphics output
stmt_plot:
    rts

; COLOR - set color
stmt_color:
    rts
