; Applesoft BASIC for HBC-56 - Bytecode Interpreter
;
; Copyright (c) 2026
; Licensed under MIT
;
; Executes bytecode generated by the tokenizer
;

; Zero page allocations
interp_pc          = $28   ; Program counter (bytecode offset)
interp_line        = $2A   ; Current line number
var_ptr            = $2C   ; Pointer to variable table
var_count          = $2E   ; Number of variables defined
gosub_depth        = $2F   ; GOSUB nesting depth (max 32)
for_depth          = $30   ; FOR loop nesting depth (max 16)

; Return stack (GOSUB):  $300-$31F (32 addresses = 64 bytes)
GOSUB_STACK        = $0300

; FOR loop stack:        $320-$35F (16 loop contexts = 64 bytes)
FOR_STACK          = $0320

; Variable table:        $0200-$02FF (max 256 bytes, ~30 variables at 8 bytes each)
VAR_TABLE          = $0200

; String pool:          $0360-$13FF (4KB for strings)
STRING_POOL        = $0360

; Bytecode buffer:      $1400-$79FF (user program bytecode)
BYTECODE_BUFFER    = $1400

; =============================================================================
; interpret: Main interpreter loop
;
; Input:
;   BYTECODE_BUFFER: Contains bytecode to execute
;
; Output:
;   Program execution complete or error
; =============================================================================
interpret:
    lda #0
    sta interp_pc
    sta interp_pc + 1
    sta var_count
    sta gosub_depth
    sta for_depth

    ; Main execution loop
.mainloop:
    ; Read next bytecode token
    lda BYTECODE_BUFFER, X
    
    ; Dispatch based on token type
    cmp #$00
    bcc .is_keyword
    cmp #$20
    bcc .unknown_token
    cmp #$40
    beq .is_variable
    cmp #$41
    beq .is_number
    cmp #$42
    beq .is_string
    cmp #$43
    beq .is_operator
    cmp #$44
    beq .is_delimiter
    
.unknown_token:
    ; Error: unknown token
    brk
    
.is_keyword:
    ; Dispatch keyword
    cmp #KW_PRINT
    beq .handle_print
    cmp #KW_GOTO
    beq .handle_goto
    cmp #KW_IF
    beq .handle_if
    cmp #KW_FOR
    beq .handle_for
    cmp #KW_NEXT
    beq .handle_next
    cmp #KW_GOSUB
    beq .handle_gosub
    cmp #KW_RETURN
    beq .handle_return
    cmp #KW_LET
    beq .handle_let
    cmp #KW_INPUT
    beq .handle_input
    cmp #KW_REM
    beq .handle_rem
    cmp #KW_END
    beq .handle_end
    
    ; Unknown keyword
    brk

.handle_print:
    ; TODO: Implement PRINT
    rts
    
.handle_goto:
    ; TODO: Implement GOTO
    rts
    
.handle_if:
    ; TODO: Implement IF/THEN
    rts
    
.handle_for:
    ; TODO: Implement FOR
    rts
    
.handle_next:
    ; TODO: Implement NEXT
    rts
    
.handle_gosub:
    ; TODO: Implement GOSUB
    rts
    
.handle_return:
    ; TODO: Implement RETURN
    rts
    
.handle_let:
    ; TODO: Implement LET (assignment)
    rts
    
.handle_input:
    ; TODO: Implement INPUT
    rts
    
.handle_rem:
    ; TODO: Implement REM (skip to newline)
    rts
    
.handle_end:
    ; Program complete
    rts

.is_variable:
    ; Variable reference
    ; TODO: Implement variable access
    rts
    
.is_number:
    ; Number literal
    ; TODO: Implement number literal
    rts
    
.is_string:
    ; String literal
    ; TODO: Implement string literal
    rts
    
.is_operator:
    ; Operator (binary or unary)
    ; TODO: Implement operator handling
    rts
    
.is_delimiter:
    ; Delimiter (comma, colon, paren, newline)
    ; TODO: Implement delimiter handling
    rts

; =============================================================================
; var_lookup: Find or create a variable in the symbol table
;
; Input:
;   Accumulator: Variable name (first character for quick lookup)
;
; Output:
;   Accumulator: Variable table index
;   Carry: Clear if found/created, Set if table full
; =============================================================================
var_lookup:
    ; TODO: Implement variable lookup
    clc
    rts
