; Applesoft BASIC for HBC-56 - Interpreter
;
; Executes bytecode generated by the tokenizer
;

; Zero page allocations
interp_pc          = $28   ; Program counter in bytecode
interp_sp          = $2A   ; Stack pointer
for_depth          = $2B   ; FOR loop nesting depth
gosub_depth        = $2C   ; GOSUB nesting depth
current_stmt       = $2D   ; Current statement token

; Variable storage area
*=$0200
variable_table:
    !fill 256, 0            ; Variables: max 32 variables

; String pool
*=$0300
string_pool:
    !fill 4096, 0           ; String storage: 4KB

; GOSUB return stack
*=$1300
gosub_stack:
    !fill 64, 0             ; 32 return addresses (2 bytes each)

; FOR loop stack
*=$1340
for_stack:
    !fill 64, 0             ; 16 FOR contexts (4 bytes each)

; User program bytecode
*=$1400
program_buffer:
    !fill 30720, 0          ; User program: ~30KB max

; =============================================================================
; interpret: Main bytecode interpreter loop
; Input:  program_buffer = bytecode
; Output: (program terminates)
; =============================================================================
interpret:
    php
    pha
    phx
    phy
    
    lda #0
    sta for_depth
    sta gosub_depth
    sta interp_pc
    sta interp_pc+1
    
    ; Fetch-decode-execute loop
exec_loop:
    lda (interp_pc)
    
    ; Dispatch on keyword value
    cmp #KW_PRINT
    beq do_print
    cmp #KW_INPUT
    beq do_input
    cmp #KW_LET
    beq do_let
    cmp #KW_GOTO
    beq do_goto
    cmp #KW_IF
    beq do_if
    cmp #KW_FOR
    beq do_for
    cmp #KW_NEXT
    beq do_next
    cmp #KW_GOSUB
    beq do_gosub
    cmp #KW_RETURN
    beq do_return
    cmp #KW_REM
    beq do_rem
    cmp #KW_END
    beq do_end
    
    ; Skip unknown token
    bra next_token
    
do_print:
    jsr stmt_print
    bra next_token
do_input:
    jsr stmt_input
    bra next_token
do_let:
    jsr stmt_let
    bra next_token
do_goto:
    jsr stmt_goto
    bra next_token
do_if:
    jsr stmt_if
    bra next_token
do_for:
    jsr stmt_for
    bra next_token
do_next:
    jsr stmt_next
    bra next_token
do_gosub:
    jsr stmt_gosub
    bra next_token
do_return:
    jsr stmt_return
    bra next_token
do_rem:
    jsr stmt_rem
    bra next_token
do_end:
    jsr stmt_end
    bra next_token
    
    ; Move to next token
next_token:
    inc interp_pc
    bne exec_loop
    inc interp_pc+1
    bra exec_loop

; =============================================================================
; Statement handlers - dispatched by keyword token
; =============================================================================

; PRINT - output text/expressions to screen
stmt_print:
    php
    pha
    phx
    phy
    
    ; For Phase 1: simplified - just output "OK" to indicate execution
    ; TODO: Parse and output actual expressions
    
    ply
    plx
    pla
    plp
    rts

; INPUT - read from keyboard
stmt_input:
    rts

; LET - variable assignment
stmt_let:
    rts

; GOTO - unconditional jump
stmt_goto:
    rts

; IF - conditional branch
stmt_if:
    rts

; THEN - part of IF statement
stmt_then:
    rts

; FOR - start loop
stmt_for:
    rts

; NEXT - end loop
stmt_next:
    rts

; GOSUB - call subroutine
stmt_gosub:
    rts

; RETURN - return from subroutine
stmt_return:
    rts

; REM - comment (already skipped by tokenizer)
stmt_rem:
    rts

; END - terminate program
stmt_end:
    rts

; RUN - start execution
stmt_run:
    rts

; NEW - clear program
stmt_new:
    rts

; PLOT - graphics output
stmt_plot:
    rts

; COLOR - set color
stmt_color:
    rts
